# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'books_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BooksScreen(object):
    def setupUi(self, BooksScreen):
        BooksScreen.setObjectName("BooksScreen")
        self.verticalLayout = QtWidgets.QVBoxLayout(BooksScreen)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_heading = QtWidgets.QLabel(BooksScreen)
        self.label_heading.setAlignment(QtCore.Qt.AlignCenter)
        self.label_heading.setObjectName("label_heading")
        self.verticalLayout.addWidget(self.label_heading)
        self.titleInput = QtWidgets.QLineEdit(BooksScreen)
        self.titleInput.setObjectName("titleInput")
        self.verticalLayout.addWidget(self.titleInput)
        self.saveButton = QtWidgets.QPushButton(BooksScreen)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout.addWidget(self.saveButton)

        self.retranslateUi(BooksScreen)
        QtCore.QMetaObject.connectSlotsByName(BooksScreen)

    def retranslateUi(self, BooksScreen):
        _translate = QtCore.QCoreApplication.translate
        self.label_heading.setText(_translate("BooksScreen", "📚 Book Management"))
        self.titleInput.setPlaceholderText(_translate("BooksScreen", "Enter book title"))
        self.saveButton.setText(_translate("BooksScreen", "➕ Save Book"))
