# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/screens/CU06_login_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login_screen(object):
    def setupUi(self, login_screen):
        login_screen.setObjectName("login_screen")
        login_screen.resize(400, 420)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(login_screen.sizePolicy().hasHeightForWidth())
        login_screen.setSizePolicy(sizePolicy)
        login_screen.setMinimumSize(QtCore.QSize(400, 420))
        login_screen.setMaximumSize(QtCore.QSize(400, 420))
        login_screen.setWindowTitle("ArchiBox - Login")
        self.access = QtWidgets.QPushButton(login_screen)
        self.access.setGeometry(QtCore.QRect(140, 360, 120, 30))
        font = QtGui.QFont()
        font.setFamily("Mononoki Nerd Font Mono")
        font.setPointSize(12)
        self.access.setFont(font)
        self.access.setObjectName("access")
        self.email_in = QtWidgets.QLineEdit(login_screen)
        self.email_in.setGeometry(QtCore.QRect(10, 250, 381, 31))
        self.email_in.setObjectName("email_in")
        self.email_ask = QtWidgets.QLabel(login_screen)
        self.email_ask.setGeometry(QtCore.QRect(20, 220, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Mononoki Nerd Font Mono")
        font.setPointSize(14)
        self.email_ask.setFont(font)
        self.email_ask.setObjectName("email_ask")
        self.password_ask_2 = QtWidgets.QLabel(login_screen)
        self.password_ask_2.setGeometry(QtCore.QRect(20, 290, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Mononoki Nerd Font Mono")
        font.setPointSize(14)
        self.password_ask_2.setFont(font)
        self.password_ask_2.setObjectName("password_ask_2")
        self.password_in = QtWidgets.QLineEdit(login_screen)
        self.password_in.setGeometry(QtCore.QRect(10, 320, 381, 31))
        self.password_in.setObjectName("password_in")
        self.err_display = QtWidgets.QLabel(login_screen)
        self.err_display.setGeometry(QtCore.QRect(10, 400, 381, 16))
        font = QtGui.QFont()
        font.setFamily("Mononoki Nerd Font Mono")
        self.err_display.setFont(font)
        self.err_display.setObjectName("err_display")
        self.bannerLabel = QtWidgets.QLabel(login_screen)
        self.bannerLabel.setGeometry(QtCore.QRect(0, 0, 400, 200))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bannerLabel.sizePolicy().hasHeightForWidth())
        self.bannerLabel.setSizePolicy(sizePolicy)
        self.bannerLabel.setMinimumSize(QtCore.QSize(400, 200))
        self.bannerLabel.setMaximumSize(QtCore.QSize(400, 200))
        self.bannerLabel.setText("")
        self.bannerLabel.setObjectName("bannerLabel")

        self.retranslateUi(login_screen)
        QtCore.QMetaObject.connectSlotsByName(login_screen)

    def retranslateUi(self, login_screen):
        _translate = QtCore.QCoreApplication.translate
        self.access.setText(_translate("login_screen", "Acceder"))
        self.email_ask.setText(_translate("login_screen", "E-mail:"))
        self.password_ask_2.setText(_translate("login_screen", "Contraseña:"))
        self.err_display.setText(_translate("login_screen", "ver 1.2.4"))
