# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './CU01_register_book_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_register_book_screen(object):
    def setupUi(self, register_book_screen):
        register_book_screen.setObjectName("register_book_screen")
        self.verticalLayout = QtWidgets.QVBoxLayout(register_book_screen)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_heading = QtWidgets.QLabel(register_book_screen)
        self.label_heading.setAlignment(QtCore.Qt.AlignCenter)
        self.label_heading.setObjectName("label_heading")
        self.verticalLayout.addWidget(self.label_heading)
        self.titleInput = QtWidgets.QLineEdit(register_book_screen)
        self.titleInput.setObjectName("titleInput")
        self.verticalLayout.addWidget(self.titleInput)
        self.saveButton = QtWidgets.QPushButton(register_book_screen)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout.addWidget(self.saveButton)

        self.retranslateUi(register_book_screen)
        QtCore.QMetaObject.connectSlotsByName(register_book_screen)

    def retranslateUi(self, register_book_screen):
        _translate = QtCore.QCoreApplication.translate
        self.label_heading.setText(_translate("register_book_screen", "📚 register book screen Screen"))
        self.titleInput.setPlaceholderText(_translate("register_book_screen", "Enter text..."))
        self.saveButton.setText(_translate("register_book_screen", "➕ Confirm"))
