# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './CU02_register_condition_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_register_condition_screen(object):
    def setupUi(self, register_condition_screen):
        register_condition_screen.setObjectName("register_condition_screen")
        self.verticalLayout = QtWidgets.QVBoxLayout(register_condition_screen)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_heading = QtWidgets.QLabel(register_condition_screen)
        self.label_heading.setAlignment(QtCore.Qt.AlignCenter)
        self.label_heading.setObjectName("label_heading")
        self.verticalLayout.addWidget(self.label_heading)
        self.titleInput = QtWidgets.QLineEdit(register_condition_screen)
        self.titleInput.setObjectName("titleInput")
        self.verticalLayout.addWidget(self.titleInput)
        self.saveButton = QtWidgets.QPushButton(register_condition_screen)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout.addWidget(self.saveButton)

        self.retranslateUi(register_condition_screen)
        QtCore.QMetaObject.connectSlotsByName(register_condition_screen)

    def retranslateUi(self, register_condition_screen):
        _translate = QtCore.QCoreApplication.translate
        self.label_heading.setText(_translate("register_condition_screen", "📚 register condition screen Screen"))
        self.titleInput.setPlaceholderText(_translate("register_condition_screen", "Enter text..."))
        self.saveButton.setText(_translate("register_condition_screen", "➕ Confirm"))
