# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CU03_restore_book_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_restore_book_screen(object):
    def setupUi(self, restore_book_screen):
        restore_book_screen.setObjectName("restore_book_screen")
        restore_book_screen.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(restore_book_screen)
        self.verticalLayout.setObjectName("verticalLayout")
        self.libroLabel = QtWidgets.QLabel(restore_book_screen)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.libroLabel.setFont(font)
        self.libroLabel.setObjectName("libroLabel")
        self.verticalLayout.addWidget(self.libroLabel)
        self.libroIdInput = QtWidgets.QLineEdit(restore_book_screen)
        self.libroIdInput.setObjectName("libroIdInput")
        self.verticalLayout.addWidget(self.libroIdInput)
        self.estadoLabel = QtWidgets.QLabel(restore_book_screen)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.estadoLabel.setFont(font)
        self.estadoLabel.setObjectName("estadoLabel")
        self.verticalLayout.addWidget(self.estadoLabel)
        self.condicionComboBox = QtWidgets.QComboBox(restore_book_screen)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.condicionComboBox.setFont(font)
        self.condicionComboBox.setObjectName("condicionComboBox")
        self.verticalLayout.addWidget(self.condicionComboBox)
        self.fechaInicioLabel = QtWidgets.QLabel(restore_book_screen)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fechaInicioLabel.setFont(font)
        self.fechaInicioLabel.setObjectName("fechaInicioLabel")
        self.verticalLayout.addWidget(self.fechaInicioLabel)
        self.fechaInicioEdit = QtWidgets.QDateEdit(restore_book_screen)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fechaInicioEdit.setFont(font)
        self.fechaInicioEdit.setCalendarPopup(True)
        self.fechaInicioEdit.setObjectName("fechaInicioEdit")
        self.verticalLayout.addWidget(self.fechaInicioEdit)
        self.fechaFinLabel = QtWidgets.QLabel(restore_book_screen)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fechaFinLabel.setFont(font)
        self.fechaFinLabel.setObjectName("fechaFinLabel")
        self.verticalLayout.addWidget(self.fechaFinLabel)
        self.fechaFinEdit = QtWidgets.QDateEdit(restore_book_screen)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fechaFinEdit.setFont(font)
        self.fechaFinEdit.setCalendarPopup(True)
        self.fechaFinEdit.setObjectName("fechaFinEdit")
        self.verticalLayout.addWidget(self.fechaFinEdit)
        self.mensajeLabel = QtWidgets.QLabel(restore_book_screen)
        self.mensajeLabel.setText("")
        self.mensajeLabel.setObjectName("mensajeLabel")
        self.verticalLayout.addWidget(self.mensajeLabel)
        self.guardarButton = QtWidgets.QPushButton(restore_book_screen)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.guardarButton.setFont(font)
        self.guardarButton.setObjectName("guardarButton")
        self.verticalLayout.addWidget(self.guardarButton)

        self.retranslateUi(restore_book_screen)
        QtCore.QMetaObject.connectSlotsByName(restore_book_screen)

    def retranslateUi(self, restore_book_screen):
        _translate = QtCore.QCoreApplication.translate
        restore_book_screen.setWindowTitle(
            _translate("restore_book_screen", "Restauración física del libro")
        )
        self.libroLabel.setText(
            _translate("restore_book_screen", "ID del Libro a restaurar:")
        )
        self.estadoLabel.setText(_translate("restore_book_screen", "Condición física:"))
        self.fechaInicioLabel.setText(
            _translate("restore_book_screen", "Fecha de inicio:")
        )
        self.fechaFinLabel.setText(
            _translate("restore_book_screen", "Fecha de finalización:")
        )
        self.guardarButton.setText(
            _translate("restore_book_screen", "Guardar restauración")
        )
