# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CU02_register_condition_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_register_condition_screen(object):
    def setupUi(self, register_condition_screen):
        register_condition_screen.setObjectName("register_condition_screen")
        register_condition_screen.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(register_condition_screen)
        self.verticalLayout.setObjectName("verticalLayout")
        self.libroLabel = QtWidgets.QLabel(register_condition_screen)
        self.libroLabel.setObjectName("libroLabel")
        self.verticalLayout.addWidget(self.libroLabel)
        self.libroLabel_2 = QtWidgets.QLabel(register_condition_screen)
        self.libroLabel_2.setObjectName("libroLabel_2")
        self.verticalLayout.addWidget(self.libroLabel_2)
        self.libroIdInput = QtWidgets.QLineEdit(register_condition_screen)
        self.libroIdInput.setObjectName("libroIdInput")
        self.verticalLayout.addWidget(self.libroIdInput)
        self.estadoLabel = QtWidgets.QLabel(register_condition_screen)
        self.estadoLabel.setObjectName("estadoLabel")
        self.verticalLayout.addWidget(self.estadoLabel)
        self.condicionComboBox = QtWidgets.QComboBox(register_condition_screen)
        self.condicionComboBox.setObjectName("condicionComboBox")
        self.verticalLayout.addWidget(self.condicionComboBox)
        self.fechaInicioLabel = QtWidgets.QLabel(register_condition_screen)
        self.fechaInicioLabel.setObjectName("fechaInicioLabel")
        self.verticalLayout.addWidget(self.fechaInicioLabel)
        self.fechaInicioEdit = QtWidgets.QDateEdit(register_condition_screen)
        self.fechaInicioEdit.setCalendarPopup(True)
        self.fechaInicioEdit.setObjectName("fechaInicioEdit")
        self.verticalLayout.addWidget(self.fechaInicioEdit)
        self.fechaFinLabel = QtWidgets.QLabel(register_condition_screen)
        self.fechaFinLabel.setObjectName("fechaFinLabel")
        self.verticalLayout.addWidget(self.fechaFinLabel)
        self.fechaFinEdit = QtWidgets.QDateEdit(register_condition_screen)
        self.fechaFinEdit.setCalendarPopup(True)
        self.fechaFinEdit.setObjectName("fechaFinEdit")
        self.verticalLayout.addWidget(self.fechaFinEdit)
        self.mensajeLabel = QtWidgets.QLabel(register_condition_screen)
        self.mensajeLabel.setText("")
        self.mensajeLabel.setObjectName("mensajeLabel")
        self.verticalLayout.addWidget(self.mensajeLabel)
        self.guardarButton = QtWidgets.QPushButton(register_condition_screen)
        self.guardarButton.setObjectName("guardarButton")
        self.verticalLayout.addWidget(self.guardarButton)

        self.retranslateUi(register_condition_screen)
        QtCore.QMetaObject.connectSlotsByName(register_condition_screen)

    def retranslateUi(self, register_condition_screen):
        _translate = QtCore.QCoreApplication.translate
        register_condition_screen.setWindowTitle(_translate("register_condition_screen", "Revisión física del libro"))
        self.libroLabel.setText(_translate("register_condition_screen", "Libro a revisar:"))
        self.libroLabel_2.setText(_translate("register_condition_screen", "ID del Libro:"))
        self.estadoLabel.setText(_translate("register_condition_screen", "Condición física:"))
        self.fechaInicioLabel.setText(_translate("register_condition_screen", "Fecha de inicio:"))
        self.fechaFinLabel.setText(_translate("register_condition_screen", "Fecha de finalización:"))
        self.guardarButton.setText(_translate("register_condition_screen", "Guardar revisión"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    register_condition_screen = QtWidgets.QWidget()
    ui = Ui_register_condition_screen()
    ui.setupUi(register_condition_screen)
    register_condition_screen.show()
    #sys.exit(app.exec_())