# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CU25_create_category_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_create_category_screen(object):
    def setupUi(self, create_category_screen):
        create_category_screen.setObjectName("create_category_screen")
        create_category_screen.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(create_category_screen)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(create_category_screen)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.nombreInput = QtWidgets.QLineEdit(create_category_screen)
        self.nombreInput.setObjectName("nombreInput")
        self.verticalLayout.addWidget(self.nombreInput)
        self.label_2 = QtWidgets.QLabel(create_category_screen)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.descripcionInput = QtWidgets.QTextEdit(create_category_screen)
        self.descripcionInput.setObjectName("descripcionInput")
        self.verticalLayout.addWidget(self.descripcionInput)
        self.errorLabel = QtWidgets.QLabel(create_category_screen)
        self.errorLabel.setStyleSheet("color: red;")
        self.errorLabel.setText("")
        self.errorLabel.setObjectName("errorLabel")
        self.verticalLayout.addWidget(self.errorLabel)
        self.saveButton = QtWidgets.QPushButton(create_category_screen)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout.addWidget(self.saveButton)

        self.retranslateUi(create_category_screen)
        QtCore.QMetaObject.connectSlotsByName(create_category_screen)

    def retranslateUi(self, create_category_screen):
        _translate = QtCore.QCoreApplication.translate
        create_category_screen.setWindowTitle(_translate("create_category_screen", "Crear nueva categoría"))
        self.label.setText(_translate("create_category_screen", "Nombre de la categoría:"))
        self.label_2.setText(_translate("create_category_screen", "Descripción (opcional):"))
        self.saveButton.setText(_translate("create_category_screen", "Guardar categoría"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    create_category_screen = QtWidgets.QWidget()
    ui = Ui_create_category_screen()
    ui.setupUi(create_category_screen)
    create_category_screen.show()
    sys.exit(app.exec_())