# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './CU08_generate_report_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_generate_report_screen(object):
    def setupUi(self, generate_report_screen):
        generate_report_screen.setObjectName("generate_report_screen")
        self.verticalLayout = QtWidgets.QVBoxLayout(generate_report_screen)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_heading = QtWidgets.QLabel(generate_report_screen)
        self.label_heading.setAlignment(QtCore.Qt.AlignCenter)
        self.label_heading.setObjectName("label_heading")
        self.verticalLayout.addWidget(self.label_heading)
        self.titleInput = QtWidgets.QLineEdit(generate_report_screen)
        self.titleInput.setObjectName("titleInput")
        self.verticalLayout.addWidget(self.titleInput)
        self.saveButton = QtWidgets.QPushButton(generate_report_screen)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout.addWidget(self.saveButton)

        self.retranslateUi(generate_report_screen)
        QtCore.QMetaObject.connectSlotsByName(generate_report_screen)

    def retranslateUi(self, generate_report_screen):
        _translate = QtCore.QCoreApplication.translate
        self.label_heading.setText(
            _translate("generate_report_screen", "📚 generate report screen Screen")
        )
        self.titleInput.setPlaceholderText(
            _translate("generate_report_screen", "Enter text...")
        )
        self.saveButton.setText(_translate("generate_report_screen", "➕ Confirm"))
