# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './CU14_notification_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_notification_screen(object):
    def setupUi(self, notification_screen):
        notification_screen.setObjectName("notification_screen")
        self.verticalLayout = QtWidgets.QVBoxLayout(notification_screen)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_heading = QtWidgets.QLabel(notification_screen)
        self.label_heading.setAlignment(QtCore.Qt.AlignCenter)
        self.label_heading.setObjectName("label_heading")
        self.verticalLayout.addWidget(self.label_heading)
        self.titleInput = QtWidgets.QLineEdit(notification_screen)
        self.titleInput.setObjectName("titleInput")
        self.verticalLayout.addWidget(self.titleInput)
        self.saveButton = QtWidgets.QPushButton(notification_screen)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout.addWidget(self.saveButton)

        self.retranslateUi(notification_screen)
        QtCore.QMetaObject.connectSlotsByName(notification_screen)

    def retranslateUi(self, notification_screen):
        _translate = QtCore.QCoreApplication.translate
        self.label_heading.setText(_translate("notification_screen", "📚 notification screen Screen"))
        self.titleInput.setPlaceholderText(_translate("notification_screen", "Enter text..."))
        self.saveButton.setText(_translate("notification_screen", "➕ Confirm"))
