# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CU05_classify_book_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_classify_book_screen(object):
    def setupUi(self, classify_book_screen):
        classify_book_screen.setObjectName("classify_book_screen")
        classify_book_screen.resize(500, 400)
        self.verticalLayout = QtWidgets.QVBoxLayout(classify_book_screen)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(classify_book_screen)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.book_combo = QtWidgets.QComboBox(classify_book_screen)
        self.book_combo.setObjectName("book_combo")
        self.verticalLayout.addWidget(self.book_combo)
        self.label_2 = QtWidgets.QLabel(classify_book_screen)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.category_combo = QtWidgets.QComboBox(classify_book_screen)
        self.category_combo.setObjectName("category_combo")
        self.verticalLayout.addWidget(self.category_combo)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(classify_book_screen)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.title_display = QtWidgets.QLabel(classify_book_screen)
        self.title_display.setText("")
        self.title_display.setObjectName("title_display")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.title_display
        )
        self.label_4 = QtWidgets.QLabel(classify_book_screen)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.author_display = QtWidgets.QLabel(classify_book_screen)
        self.author_display.setText("")
        self.author_display.setObjectName("author_display")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.FieldRole, self.author_display
        )
        self.label_5 = QtWidgets.QLabel(classify_book_screen)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.current_category_display = QtWidgets.QLabel(classify_book_screen)
        self.current_category_display.setText("")
        self.current_category_display.setObjectName("current_category_display")
        self.formLayout.setWidget(
            2, QtWidgets.QFormLayout.FieldRole, self.current_category_display
        )
        self.verticalLayout.addLayout(self.formLayout)
        self.save_button = QtWidgets.QPushButton(classify_book_screen)
        self.save_button.setObjectName("save_button")
        self.verticalLayout.addWidget(self.save_button)

        self.retranslateUi(classify_book_screen)
        QtCore.QMetaObject.connectSlotsByName(classify_book_screen)

    def retranslateUi(self, classify_book_screen):
        _translate = QtCore.QCoreApplication.translate
        classify_book_screen.setWindowTitle(
            _translate("classify_book_screen", "Clasificar Libro")
        )
        self.label.setText(_translate("classify_book_screen", "Libro a clasificar:"))
        self.label_2.setText(_translate("classify_book_screen", "Categoría:"))
        self.label_3.setText(_translate("classify_book_screen", "Título:"))
        self.label_4.setText(_translate("classify_book_screen", "Autor:"))
        self.label_5.setText(_translate("classify_book_screen", "Categoría actual:"))
        self.save_button.setText(
            _translate("classify_book_screen", "Guardar Clasificación")
        )


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    classify_book_screen = QtWidgets.QWidget()
    ui = Ui_classify_book_screen()
    ui.setupUi(classify_book_screen)
    classify_book_screen.show()
    sys.exit(app.exec_())
