# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CU18_search_users_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_search_users_screen(object):
    def setupUi(self, search_users_screen):
        search_users_screen.setObjectName("search_users_screen")
        search_users_screen.resize(800, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(search_users_screen)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_heading = QtWidgets.QLabel(search_users_screen)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_heading.setFont(font)
        self.label_heading.setAlignment(QtCore.Qt.AlignCenter)
        self.label_heading.setObjectName("label_heading")
        self.verticalLayout.addWidget(self.label_heading)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(10, 10, 10, 10)
        self.formLayout.setObjectName("formLayout")
        self.label_nombre = QtWidgets.QLabel(search_users_screen)
        self.label_nombre.setObjectName("label_nombre")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_nombre)
        self.nombres_input = QtWidgets.QLineEdit(search_users_screen)
        self.nombres_input.setObjectName("nombres_input")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.nombres_input
        )
        self.label_apellidos = QtWidgets.QLabel(search_users_screen)
        self.label_apellidos.setObjectName("label_apellidos")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.LabelRole, self.label_apellidos
        )
        self.apellidos_input = QtWidgets.QLineEdit(search_users_screen)
        self.apellidos_input.setObjectName("apellidos_input")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.FieldRole, self.apellidos_input
        )
        self.label_correo = QtWidgets.QLabel(search_users_screen)
        self.label_correo.setObjectName("label_correo")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_correo)
        self.correo_input = QtWidgets.QLineEdit(search_users_screen)
        self.correo_input.setObjectName("correo_input")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.correo_input)
        self.label_rol = QtWidgets.QLabel(search_users_screen)
        self.label_rol.setObjectName("label_rol")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_rol)
        self.rol_combo = QtWidgets.QComboBox(search_users_screen)
        self.rol_combo.setObjectName("rol_combo")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.rol_combo)
        self.label_estado = QtWidgets.QLabel(search_users_screen)
        self.label_estado.setObjectName("label_estado")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_estado)
        self.estado_combo = QtWidgets.QComboBox(search_users_screen)
        self.estado_combo.setObjectName("estado_combo")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.estado_combo)
        self.verticalLayout.addLayout(self.formLayout)
        self.search_button = QtWidgets.QPushButton(search_users_screen)
        self.search_button.setObjectName("search_button")
        self.verticalLayout.addWidget(self.search_button)
        self.results_table = QtWidgets.QTableWidget(search_users_screen)
        self.results_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.results_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.results_table.setObjectName("results_table")
        self.results_table.setColumnCount(5)
        self.results_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.results_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.results_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.results_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.results_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.results_table.setHorizontalHeaderItem(4, item)
        self.results_table.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.results_table)

        self.retranslateUi(search_users_screen)
        QtCore.QMetaObject.connectSlotsByName(search_users_screen)

    def retranslateUi(self, search_users_screen):
        _translate = QtCore.QCoreApplication.translate
        search_users_screen.setWindowTitle(
            _translate("search_users_screen", "Búsqueda de Usuarios")
        )
        self.label_heading.setText(
            _translate("search_users_screen", "👥 Búsqueda de Usuarios")
        )
        self.label_nombre.setText(_translate("search_users_screen", "Nombres:"))
        self.label_apellidos.setText(_translate("search_users_screen", "Apellidos:"))
        self.label_correo.setText(
            _translate("search_users_screen", "Correo Electrónico:")
        )
        self.label_rol.setText(_translate("search_users_screen", "Rol:"))
        self.label_estado.setText(_translate("search_users_screen", "Estado:"))
        self.search_button.setText(_translate("search_users_screen", "Buscar Usuarios"))
        item = self.results_table.horizontalHeaderItem(0)
        item.setText(_translate("search_users_screen", "Nombres"))
        item = self.results_table.horizontalHeaderItem(1)
        item.setText(_translate("search_users_screen", "Apellidos"))
        item = self.results_table.horizontalHeaderItem(2)
        item.setText(_translate("search_users_screen", "Correo Electrónico"))
        item = self.results_table.horizontalHeaderItem(3)
        item.setText(_translate("search_users_screen", "Rol"))
        item = self.results_table.horizontalHeaderItem(4)
        item.setText(_translate("search_users_screen", "Estado"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    search_users_screen = QtWidgets.QWidget()
    ui = Ui_search_users_screen()
    ui.setupUi(search_users_screen)
    search_users_screen.show()
    sys.exit(app.exec_())
