# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './CU20_change_password_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_change_password_screen(object):
    def setupUi(self, change_password_screen):
        change_password_screen.setObjectName("change_password_screen")
        self.verticalLayout = QtWidgets.QVBoxLayout(change_password_screen)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_heading = QtWidgets.QLabel(change_password_screen)
        self.label_heading.setAlignment(QtCore.Qt.AlignCenter)
        self.label_heading.setObjectName("label_heading")
        self.verticalLayout.addWidget(self.label_heading)
        self.titleInput = QtWidgets.QLineEdit(change_password_screen)
        self.titleInput.setObjectName("titleInput")
        self.verticalLayout.addWidget(self.titleInput)
        self.saveButton = QtWidgets.QPushButton(change_password_screen)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout.addWidget(self.saveButton)

        self.retranslateUi(change_password_screen)
        QtCore.QMetaObject.connectSlotsByName(change_password_screen)

    def retranslateUi(self, change_password_screen):
        _translate = QtCore.QCoreApplication.translate
        self.label_heading.setText(_translate("change_password_screen", "📚 change password screen Screen"))
        self.titleInput.setPlaceholderText(_translate("change_password_screen", "Enter text..."))
        self.saveButton.setText(_translate("change_password_screen", "➕ Confirm"))
