# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './CU25_create_category_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_create_category_screen(object):
    def setupUi(self, create_category_screen):
        create_category_screen.setObjectName("create_category_screen")
        self.verticalLayout = QtWidgets.QVBoxLayout(create_category_screen)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_heading = QtWidgets.QLabel(create_category_screen)
        self.label_heading.setAlignment(QtCore.Qt.AlignCenter)
        self.label_heading.setObjectName("label_heading")
        self.verticalLayout.addWidget(self.label_heading)
        self.titleInput = QtWidgets.QLineEdit(create_category_screen)
        self.titleInput.setObjectName("titleInput")
        self.verticalLayout.addWidget(self.titleInput)
        self.saveButton = QtWidgets.QPushButton(create_category_screen)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout.addWidget(self.saveButton)

        self.retranslateUi(create_category_screen)
        QtCore.QMetaObject.connectSlotsByName(create_category_screen)

    def retranslateUi(self, create_category_screen):
        _translate = QtCore.QCoreApplication.translate
        self.label_heading.setText(_translate("create_category_screen", "📚 create category screen Screen"))
        self.titleInput.setPlaceholderText(_translate("create_category_screen", "Enter text..."))
        self.saveButton.setText(_translate("create_category_screen", "➕ Confirm"))
