# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './CU21_restore_password_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_restore_password_screen(object):
    def setupUi(self, restore_password_screen):
        restore_password_screen.setObjectName("restore_password_screen")
        self.verticalLayout = QtWidgets.QVBoxLayout(restore_password_screen)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_heading = QtWidgets.QLabel(restore_password_screen)
        self.label_heading.setAlignment(QtCore.Qt.AlignCenter)
        self.label_heading.setObjectName("label_heading")
        self.verticalLayout.addWidget(self.label_heading)
        self.titleInput = QtWidgets.QLineEdit(restore_password_screen)
        self.titleInput.setObjectName("titleInput")
        self.verticalLayout.addWidget(self.titleInput)
        self.saveButton = QtWidgets.QPushButton(restore_password_screen)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout.addWidget(self.saveButton)

        self.retranslateUi(restore_password_screen)
        QtCore.QMetaObject.connectSlotsByName(restore_password_screen)

    def retranslateUi(self, restore_password_screen):
        _translate = QtCore.QCoreApplication.translate
        self.label_heading.setText(
            _translate("restore_password_screen", "📚 restore password screen Screen")
        )
        self.titleInput.setPlaceholderText(
            _translate("restore_password_screen", "Enter text...")
        )
        self.saveButton.setText(_translate("restore_password_screen", "➕ Confirm"))
