# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './CU18_search_users_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_search_users_screen(object):
    def setupUi(self, search_users_screen):
        search_users_screen.setObjectName("search_users_screen")
        self.verticalLayout = QtWidgets.QVBoxLayout(search_users_screen)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_heading = QtWidgets.QLabel(search_users_screen)
        self.label_heading.setAlignment(QtCore.Qt.AlignCenter)
        self.label_heading.setObjectName("label_heading")
        self.verticalLayout.addWidget(self.label_heading)
        self.titleInput = QtWidgets.QLineEdit(search_users_screen)
        self.titleInput.setObjectName("titleInput")
        self.verticalLayout.addWidget(self.titleInput)
        self.saveButton = QtWidgets.QPushButton(search_users_screen)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout.addWidget(self.saveButton)

        self.retranslateUi(search_users_screen)
        QtCore.QMetaObject.connectSlotsByName(search_users_screen)

    def retranslateUi(self, search_users_screen):
        _translate = QtCore.QCoreApplication.translate
        self.label_heading.setText(_translate("search_users_screen", "📚 search users screen Screen"))
        self.titleInput.setPlaceholderText(_translate("search_users_screen", "Enter text..."))
        self.saveButton.setText(_translate("search_users_screen", "➕ Confirm"))
