# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/screens/CU09_create_user_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_create_user_screen(object):
    def setupUi(self, create_user_screen):
        create_user_screen.setObjectName("create_user_screen")
        create_user_screen.resize(684, 440)
        self.verticalLayout = QtWidgets.QVBoxLayout(create_user_screen)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_heading = QtWidgets.QLabel(create_user_screen)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_heading.setFont(font)
        self.label_heading.setAlignment(QtCore.Qt.AlignCenter)
        self.label_heading.setObjectName("label_heading")
        self.verticalLayout.addWidget(self.label_heading)
        self.label_nombres = QtWidgets.QLabel(create_user_screen)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_nombres.setFont(font)
        self.label_nombres.setObjectName("label_nombres")
        self.verticalLayout.addWidget(self.label_nombres)
        self.nombresInput = QtWidgets.QLineEdit(create_user_screen)
        self.nombresInput.setObjectName("nombresInput")
        self.verticalLayout.addWidget(self.nombresInput)
        self.label_apellidos = QtWidgets.QLabel(create_user_screen)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_apellidos.setFont(font)
        self.label_apellidos.setObjectName("label_apellidos")
        self.verticalLayout.addWidget(self.label_apellidos)
        self.apellidosInput = QtWidgets.QLineEdit(create_user_screen)
        self.apellidosInput.setObjectName("apellidosInput")
        self.verticalLayout.addWidget(self.apellidosInput)
        self.label_email = QtWidgets.QLabel(create_user_screen)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_email.setFont(font)
        self.label_email.setObjectName("label_email")
        self.verticalLayout.addWidget(self.label_email)
        self.emailInput = QtWidgets.QLineEdit(create_user_screen)
        self.emailInput.setObjectName("emailInput")
        self.verticalLayout.addWidget(self.emailInput)
        self.label_password = QtWidgets.QLabel(create_user_screen)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_password.setFont(font)
        self.label_password.setObjectName("label_password")
        self.verticalLayout.addWidget(self.label_password)
        self.passwordInput = QtWidgets.QLineEdit(create_user_screen)
        self.passwordInput.setInputMethodHints(QtCore.Qt.ImhNone)
        self.passwordInput.setObjectName("passwordInput")
        self.verticalLayout.addWidget(self.passwordInput)
        self.label_rol = QtWidgets.QLabel(create_user_screen)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_rol.setFont(font)
        self.label_rol.setObjectName("label_rol")
        self.verticalLayout.addWidget(self.label_rol)
        self.rolComboBox = QtWidgets.QComboBox(create_user_screen)
        self.rolComboBox.setObjectName("rolComboBox")
        self.verticalLayout.addWidget(self.rolComboBox)
        self.saveButton = QtWidgets.QPushButton(create_user_screen)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout.addWidget(self.saveButton)
        self.errorLabel = QtWidgets.QLabel(create_user_screen)
        self.errorLabel.setStyleSheet("color: red;")
        self.errorLabel.setText("")
        self.errorLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.errorLabel.setObjectName("errorLabel")
        self.verticalLayout.addWidget(self.errorLabel)

        self.retranslateUi(create_user_screen)
        QtCore.QMetaObject.connectSlotsByName(create_user_screen)

    def retranslateUi(self, create_user_screen):
        _translate = QtCore.QCoreApplication.translate
        self.label_heading.setText(
            _translate("create_user_screen", "👤 Crear usuario nuevo")
        )
        self.label_nombres.setText(_translate("create_user_screen", "Nombres:"))
        self.nombresInput.setPlaceholderText(
            _translate("create_user_screen", "Ingrese nombres")
        )
        self.label_apellidos.setText(_translate("create_user_screen", "Apellidos:"))
        self.apellidosInput.setPlaceholderText(
            _translate("create_user_screen", "Ingrese apellidos")
        )
        self.label_email.setText(_translate("create_user_screen", "E-Mail:"))
        self.emailInput.setPlaceholderText(
            _translate("create_user_screen", "usuario@ejemplo.com")
        )
        self.label_password.setText(_translate("create_user_screen", "Contraseña:"))
        self.passwordInput.setPlaceholderText(
            _translate("create_user_screen", "Ingrese contraseña")
        )
        self.label_rol.setText(_translate("create_user_screen", "Rol:"))
        self.saveButton.setText(_translate("create_user_screen", "➕ Confirmar"))
