# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './CU19_assign_task_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_assign_task_screen(object):
    def setupUi(self, assign_task_screen):
        assign_task_screen.setObjectName("assign_task_screen")
        self.verticalLayout = QtWidgets.QVBoxLayout(assign_task_screen)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_heading = QtWidgets.QLabel(assign_task_screen)
        self.label_heading.setAlignment(QtCore.Qt.AlignCenter)
        self.label_heading.setObjectName("label_heading")
        self.verticalLayout.addWidget(self.label_heading)
        self.titleInput = QtWidgets.QLineEdit(assign_task_screen)
        self.titleInput.setObjectName("titleInput")
        self.verticalLayout.addWidget(self.titleInput)
        self.saveButton = QtWidgets.QPushButton(assign_task_screen)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout.addWidget(self.saveButton)

        self.retranslateUi(assign_task_screen)
        QtCore.QMetaObject.connectSlotsByName(assign_task_screen)

    def retranslateUi(self, assign_task_screen):
        _translate = QtCore.QCoreApplication.translate
        self.label_heading.setText(_translate("assign_task_screen", "📚 assign task screen Screen"))
        self.titleInput.setPlaceholderText(_translate("assign_task_screen", "Enter text..."))
        self.saveButton.setText(_translate("assign_task_screen", "➕ Confirm"))
