# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './CU10_edit_user_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_edit_user_screen(object):
    def setupUi(self, edit_user_screen):
        edit_user_screen.setObjectName("edit_user_screen")
        self.verticalLayout = QtWidgets.QVBoxLayout(edit_user_screen)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_heading = QtWidgets.QLabel(edit_user_screen)
        self.label_heading.setAlignment(QtCore.Qt.AlignCenter)
        self.label_heading.setObjectName("label_heading")
        self.verticalLayout.addWidget(self.label_heading)
        self.titleInput = QtWidgets.QLineEdit(edit_user_screen)
        self.titleInput.setObjectName("titleInput")
        self.verticalLayout.addWidget(self.titleInput)
        self.saveButton = QtWidgets.QPushButton(edit_user_screen)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout.addWidget(self.saveButton)

        self.retranslateUi(edit_user_screen)
        QtCore.QMetaObject.connectSlotsByName(edit_user_screen)

    def retranslateUi(self, edit_user_screen):
        _translate = QtCore.QCoreApplication.translate
        self.label_heading.setText(
            _translate("edit_user_screen", "📚 edit user screen Screen")
        )
        self.titleInput.setPlaceholderText(
            _translate("edit_user_screen", "Enter text...")
        )
        self.saveButton.setText(_translate("edit_user_screen", "➕ Confirm"))
