# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './CU07_query_book_history_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_query_book_history_screen(object):
    def setupUi(self, query_book_history_screen):
        query_book_history_screen.setObjectName("query_book_history_screen")
        self.verticalLayout = QtWidgets.QVBoxLayout(query_book_history_screen)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_heading = QtWidgets.QLabel(query_book_history_screen)
        self.label_heading.setAlignment(QtCore.Qt.AlignCenter)
        self.label_heading.setObjectName("label_heading")
        self.verticalLayout.addWidget(self.label_heading)
        self.titleInput = QtWidgets.QLineEdit(query_book_history_screen)
        self.titleInput.setObjectName("titleInput")
        self.verticalLayout.addWidget(self.titleInput)
        self.saveButton = QtWidgets.QPushButton(query_book_history_screen)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout.addWidget(self.saveButton)

        self.retranslateUi(query_book_history_screen)
        QtCore.QMetaObject.connectSlotsByName(query_book_history_screen)

    def retranslateUi(self, query_book_history_screen):
        _translate = QtCore.QCoreApplication.translate
        self.label_heading.setText(_translate("query_book_history_screen", "📚 query book history screen Screen"))
        self.titleInput.setPlaceholderText(_translate("query_book_history_screen", "Enter text..."))
        self.saveButton.setText(_translate("query_book_history_screen", "➕ Confirm"))
