# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './CU15_physical_qa_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_physical_qa_screen(object):
    def setupUi(self, physical_qa_screen):
        physical_qa_screen.setObjectName("physical_qa_screen")
        self.verticalLayout = QtWidgets.QVBoxLayout(physical_qa_screen)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_heading = QtWidgets.QLabel(physical_qa_screen)
        self.label_heading.setAlignment(QtCore.Qt.AlignCenter)
        self.label_heading.setObjectName("label_heading")
        self.verticalLayout.addWidget(self.label_heading)
        self.titleInput = QtWidgets.QLineEdit(physical_qa_screen)
        self.titleInput.setObjectName("titleInput")
        self.verticalLayout.addWidget(self.titleInput)
        self.saveButton = QtWidgets.QPushButton(physical_qa_screen)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout.addWidget(self.saveButton)

        self.retranslateUi(physical_qa_screen)
        QtCore.QMetaObject.connectSlotsByName(physical_qa_screen)

    def retranslateUi(self, physical_qa_screen):
        _translate = QtCore.QCoreApplication.translate
        self.label_heading.setText(_translate("physical_qa_screen", "📚 physical qa screen Screen"))
        self.titleInput.setPlaceholderText(_translate("physical_qa_screen", "Enter text..."))
        self.saveButton.setText(_translate("physical_qa_screen", "➕ Confirm"))
