# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './CU16_filter_books_by_state_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_filter_books_by_state_screen(object):
    def setupUi(self, filter_books_by_state_screen):
        filter_books_by_state_screen.setObjectName("filter_books_by_state_screen")
        self.verticalLayout = QtWidgets.QVBoxLayout(filter_books_by_state_screen)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_heading = QtWidgets.QLabel(filter_books_by_state_screen)
        self.label_heading.setAlignment(QtCore.Qt.AlignCenter)
        self.label_heading.setObjectName("label_heading")
        self.verticalLayout.addWidget(self.label_heading)
        self.titleInput = QtWidgets.QLineEdit(filter_books_by_state_screen)
        self.titleInput.setObjectName("titleInput")
        self.verticalLayout.addWidget(self.titleInput)
        self.saveButton = QtWidgets.QPushButton(filter_books_by_state_screen)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout.addWidget(self.saveButton)

        self.retranslateUi(filter_books_by_state_screen)
        QtCore.QMetaObject.connectSlotsByName(filter_books_by_state_screen)

    def retranslateUi(self, filter_books_by_state_screen):
        _translate = QtCore.QCoreApplication.translate
        self.label_heading.setText(
            _translate(
                "filter_books_by_state_screen", "📚 filter books by state screen Screen"
            )
        )
        self.titleInput.setPlaceholderText(
            _translate("filter_books_by_state_screen", "Enter text...")
        )
        self.saveButton.setText(
            _translate("filter_books_by_state_screen", "➕ Confirm")
        )
