# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './users_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UsersScreen(object):
    def setupUi(self, UsersScreen):
        UsersScreen.setObjectName("UsersScreen")
        self.verticalLayout = QtWidgets.QVBoxLayout(UsersScreen)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_heading = QtWidgets.QLabel(UsersScreen)
        self.label_heading.setAlignment(QtCore.Qt.AlignCenter)
        self.label_heading.setObjectName("label_heading")
        self.verticalLayout.addWidget(self.label_heading)
        self.emailInput = QtWidgets.QLineEdit(UsersScreen)
        self.emailInput.setObjectName("emailInput")
        self.verticalLayout.addWidget(self.emailInput)
        self.addUserButton = QtWidgets.QPushButton(UsersScreen)
        self.addUserButton.setObjectName("addUserButton")
        self.verticalLayout.addWidget(self.addUserButton)

        self.retranslateUi(UsersScreen)
        QtCore.QMetaObject.connectSlotsByName(UsersScreen)

    def retranslateUi(self, UsersScreen):
        _translate = QtCore.QCoreApplication.translate
        self.label_heading.setText(_translate("UsersScreen", "👤 User Management"))
        self.emailInput.setPlaceholderText(_translate("UsersScreen", "Enter user email"))
        self.addUserButton.setText(_translate("UsersScreen", "➕ Add User"))
