# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sideMenu = QtWidgets.QFrame(self.centralwidget)
        self.sideMenu.setMinimumWidth(150)
        self.sideMenu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sideMenu.setObjectName("sideMenu")
        self.sideMenuLayout = QtWidgets.QVBoxLayout(self.sideMenu)
        self.sideMenuLayout.setObjectName("sideMenuLayout")
        self.btn_dashboard = QtWidgets.QPushButton(self.sideMenu)
        self.btn_dashboard.setObjectName("btn_dashboard")
        self.sideMenuLayout.addWidget(self.btn_dashboard)
        self.btn_books = QtWidgets.QPushButton(self.sideMenu)
        self.btn_books.setObjectName("btn_books")
        self.sideMenuLayout.addWidget(self.btn_books)
        self.btn_users = QtWidgets.QPushButton(self.sideMenu)
        self.btn_users.setObjectName("btn_users")
        self.sideMenuLayout.addWidget(self.btn_users)
        self.horizontalLayout.addWidget(self.sideMenu)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_dashboard = QtWidgets.QWidget()
        self.page_dashboard.setObjectName("page_dashboard")
        self.layout_dashboard = QtWidgets.QVBoxLayout(self.page_dashboard)
        self.layout_dashboard.setObjectName("layout_dashboard")
        self.label_dashboard = QtWidgets.QLabel(self.page_dashboard)
        self.label_dashboard.setObjectName("label_dashboard")
        self.layout_dashboard.addWidget(self.label_dashboard)
        self.stackedWidget.addWidget(self.page_dashboard)
        self.page_books = QtWidgets.QWidget()
        self.page_books.setObjectName("page_books")
        self.layout_books = QtWidgets.QVBoxLayout(self.page_books)
        self.layout_books.setObjectName("layout_books")
        self.label_books = QtWidgets.QLabel(self.page_books)
        self.label_books.setObjectName("label_books")
        self.layout_books.addWidget(self.label_books)
        self.stackedWidget.addWidget(self.page_books)
        self.page_users = QtWidgets.QWidget()
        self.page_users.setObjectName("page_users")
        self.layout_users = QtWidgets.QVBoxLayout(self.page_users)
        self.layout_users.setObjectName("layout_users")
        self.label_users = QtWidgets.QLabel(self.page_users)
        self.label_users.setObjectName("label_users")
        self.layout_users.addWidget(self.label_users)
        self.stackedWidget.addWidget(self.page_users)
        self.horizontalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ArchiBox - Main"))
        self.btn_dashboard.setText(_translate("MainWindow", "Dashboard"))
        self.btn_books.setText(_translate("MainWindow", "Books"))
        self.btn_users.setText(_translate("MainWindow", "Users"))
        self.label_dashboard.setText(_translate("MainWindow", "Dashboard Screen"))
        self.label_books.setText(_translate("MainWindow", "Books Screen"))
        self.label_users.setText(_translate("MainWindow", "Users Screen"))
